version: '3'

services:
  grafana:
    image: grafana/grafana:6.2.5
    restart: unless-stopped
    ports:
    - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_LOG_LEVEL=debug

    volumes:
      - ./:/var/lib/grafana/plugins/utilitarian-grafana-app