{
 "title": "Utilitarian Overview",
 "time": { "from": "2019-04-10T07:32:35.329Z", "to": "2019-07-19T03:12:10.963Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Utilitarian DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Meter Readings Count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(metering_meterreading.created_at, '24h') as \"time\",\n  concat(metering_meterdevicetype.name, ' (', metering_meterdevicetype.id, ')') as \"metric\",  \n  count(metering_meterreading.value) as \"value\"\nFROM metering_meterreading\ninner join metering_meterdevice\n    ON metering_meterreading.meter_device_id = metering_meterdevice.id\nINNER JOIN metering_meterdevicetype\n  ON metering_meterdevice.type_id = metering_meterdevicetype.id\nWHERE\n  $__timeFilter(metering_meterreading.created_at)\ngroup by 1, 2\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Amount of meters",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"time\", count(*) AS \"value\"\nFROM metering_meterdevice\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of staged meter readings",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"value\", count(*) as \"time\" FROM metering_stagedmeterreading ORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Meter Device Type Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT 0                                                                       as \"time\",\n       concat(metering_meterdevicetype.name, ' (', metering_meterdevicetype.id, ')') as \"metric\",\n       count(metering_meterdevice.*)                                             as \"value\"\n\nFROM metering_meterdevice\n       INNER JOIN metering_meterdevicetype ON metering_meterdevice.type_id = metering_meterdevicetype.id\ngroup by 1, 2\nORDER BY 1;"
    }
   ]
  }
 ]
}